### ISSUE TITLE
"required => true" fields aren't required but "class => pmpro_required" does work

### ISSUE THREAD

**Issue by cliffordp** [strangerstudios/pmpro-register-helper#45]
From the [Register Helper Example](http://www.paidmembershipspro.com/2014/08/collect-information-checkout/) plugin:

```
    //define the fields
    $fields = array();
    $fields[] = new PMProRH_Field(
        'company',              // input name, will also be used as meta key
        'text',                 // type of field
        array(
            'size'=>40,         // input size
            'class'=>'company', // custom class
            'profile'=>true,    // show in user profile
            'required'=>true    // make this field required
        ));
```

The `'required'=>true` does not work (i.e. does not make the field required), but adding a `'class'=>'company pmpro_required'` does work.

I couldn't find any 'required' arguments for a new field, but I did find this code reference: https://github.com/strangerstudios/paid-memberships-pro/blob/dev/pages/checkout.php#L751

**Comment by goranefbl** [comment]
I see its fixed in latest 1.3.7 update.

**Comment by bluesteamhost** [comment]
Not fixed if you're editing a profile.  Required fields are still not required.

**Comment by dparker1005** [comment]
As @goranefbl mentioned, this issue on the checkout page should have been resolved in a previous update.

@bluesteamhost validating register helper fields when a user saves their profile is something that we are planning to look into and that we have an open issue for here: https://github.com/strangerstudios/pmpro-register-helper/issues/147

Please feel free to comment on that thread if you have further thoughts about this behavior.
